export const POST_COURSE_REQ = "POST_COURSE_REQ";
export const POST_COURSE_SUCCESS = "POST_COURSE_SUCCESS";
export const POST_COURSE_FAILIURE= "POST_COURSE_FAILIURE";


export const GET_COURSE_REQ = "GET_COURSE_REQ";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_FAILIURE= "GET_COURSE_FAILIURE";